### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by pitchandtone** [tractorcow/silverstripe-dynamiccache#28]
Is there a reason this doesn't happen out of the box? Seems like a good place to do it.

**Comment by tractorcow** [comment]
That's actually a kind of cool idea, although is the cache the best place to put it? I feel maybe this should be an extension on SSViewer.

**Comment by jonom** [comment]
I'm not sure minifying HTML is worthwhile. Probably redundant if you're using gzip and not likely to give you significant gains [compared to minifying and combining JS + CSS](http://stackoverflow.com/a/2359508/2494302). I also agree with @tractorcow that if you do want to minify HTML, this module probably isn't the right place to do it.

**Comment by dhensby** [comment]
agreed - should be closed
