### ISSUE TITLE
After / is cached, /home/ stops redirecting

### ISSUE THREAD

**Issue by axllent** [tractorcow/silverstripe-dynamiccache#29]
It would seem that after a website's root path has been cached, `/home/` stops redirecting to `/` as would generally be expected.

**Comment by tractorcow** [comment]
what headers do you get on /home/ response? (first and subsequent times).

Maybe `Location` needs to be added to the cache evasion list.

**Comment by axllent** [comment]
`/home/` initially provides a 310 redirect (ie: after a flush, before cache), however once `/` is cached, then `/home/` doesn't redirect and provides a standard 200 response.

It should be easy to replicate I think, simply load `/home/` on any cached site.

**Comment by jonom** [comment]
Have verified this issue and wonder if it's related to an issue where the form doesn't redirect back upon validation error. Maybe there's a general redirection conflict?

**Comment by tractorcow** [comment]
Fixed with #30
