### ISSUE TITLE
Multiple Caches per Page

### ISSUE THREAD

**Issue by thezenmonkey** [tractorcow/silverstripe-dynamiccache#44]
I'm evaluating using the module on an upcoming project and I was wondring if it's possible to have multiple versions of a cached page. For instance one cached version for normal visitiors and a second version for registered users. The page doesn't need to display specific user data, just reveal hidden page content for logged-in users.

**Comment by michaelbollig** [comment]
You sure can thezenmonkey. Check out https://github.com/tractorcow/silverstripe-dynamiccache#customising-cache-behaviour — by changing the cache key fragment to include whether the user is logged in or not, you can serve one version of the page to logged in users and another to normal visitors.

**Comment by tractorcow** [comment]
Cool, thanks for the response @michaelbollig ! I guess that closes this ticket. :D
