### ISSUE TITLE
Disable cache after X minutes

### ISSUE THREAD

**Issue by Firesphere** [tractorcow/silverstripe-dynamiccache#46]
I would like to cache my homepage, but have the cache dismissed after 2 minutes. Is that possible?

**Comment by jonom** [comment]
`cacheDuration` config setting should take care of it? That would be site wide though, not just on the home page.

**Comment by tractorcow** [comment]
Ah, sorry, you're right... the lifetime is global. =(
	
You could set a custom lifetime on save (maybe another cache header?) but it would have to be a PR.

**Comment by jonom** [comment]
@Firesphere could you do something like this?

```php
class HomePageCacheCustomisation extends DynamicCacheExtension
{
    public function updateCacheKeyFragments(array &$fragments) {
        // Include current time in 2 minute brackets
        $fragments[] = floor(time() / 60 * 2);
    }
}
```
Could cause some garbage to pile up in your cache but might do the trick?

**Comment by dhensby** [comment]
got a solution? time to close?
