### ISSUE TITLE
Check for Controller

### ISSUE THREAD

**Issue by Firesphere** [tractorcow/silverstripe-dynamiccache#48]
Regarding the Controller check:
> This module will allow individual pages to opt-out of caching by specifying certain headers, and will ignore caching on ajax pages or direct requests to controllers (including form submissions) by checking for any url-segments that start with an uppercase letter.

Wouldn't doing something like `!$pageThing instanceof Page`?

**Comment by tractorcow** [comment]
Oh, no, it never has access to the actual instances... only the url strings. :) This module only operates between the framework and the server; It doesn't have much access to the inner workings on request routing.

**Comment by Firesphere** [comment]
Fair enough :D I am pondering of a way to get it more reliable though. I may or may not come back to bug you :P
