### ISSUE TITLE
Composer warning with PHP 7

### ISSUE THREAD

**Issue by hpeide** [tractorcow/silverstripe-dynamiccache#64]
I get requirement warning with Composer using PHP 7.1.6

Haven't tested if it works though, will do and give feedback.

**Comment by tractorcow** [comment]
Hi @hpeide can you please show me the warning?

**Comment by SilbinaryWolf** [comment]
My assumption would be that this:
https://github.com/tractorcow/silverstripe-dynamiccache/blob/master/composer.json#L17

Needs to be >= or have an OR condition for PHP 7 and up.

**Comment by hpeide** [comment]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tractorcow/silverstripe-dynamiccache dev-master -> satisfiable by tractorcow/silverstripe-dynamiccache[dev-master].
    - tractorcow/silverstripe-dynamiccache dev-master requires php ~5.4 -> your PHP version (7.1.6) does not satisfy that requirement.

**Comment by tractorcow** [comment]
Fixed. :)
