### ISSUE TITLE
Silverstripe 4 support

### ISSUE THREAD

**Issue by Friksel** [tractorcow/silverstripe-dynamiccache#67]
I'm looking for possibilities to upgrade projects to Silverstripe 4. I saw you worked hard to upgrade Fluent for Silverstripe 4 already after working on Silverstripe 4 itself. Great work! Is there any change the dynamiccache module will get an upgrade for Silverstripe 4 too so we can keep using this great module?

**Comment by tractorcow** [comment]
I won't be upgrading this module to SilverStripe 4, I'm afraid, due to the radically different application bootstrapping in 4.x.

A 4.x implementation would be an entirely separate and brand new rewrite.

**Comment by Friksel** [comment]
I was afraid of that. It would be great if there will be a new rewrite in the future. For now I'll look for alternatives. Although there seems to be not much available for Silverstripe 4 on the moment. Even the StaticPublisher module isn't compatible with Silverstripe 4 and doesn't work well together with Fluent. Well, thanks for your reaction. Keep up the good work!

**Comment by tractorcow** [comment]
I can give advice and support if you want to make a go at it. :) I suggest to look at index.php and the implementation of the middleware classes there... a 4.x version would probably be a caching middleware of the same type.

I suspect we'll upgrade static publisher at some point as well. It's a pretty critical module!

**Comment by Friksel** [comment]
@tractorcow I have to make choices, so I once decided to specialize as a frontend developer coming from windows softwaredevelopment and backend development. But I'm keeping up with Silverstripe and php since I'm using it for dedicated purposes and company-website and I love it. But creating open source modules for Silverstripe isn't in my scope and I could't find the time to maintain them either in favour of my other work. I'd love to continue using Silverstripe 4 and so I hope this module or static publisher will get an upgrade in the near future. Guess I have to wait for it. Can't have it all ;) Thanks for now.
