### ISSUE TITLE
use standard code for flush

### ISSUE THREAD

**Issue by sunnysideup** [tractorcow/silverstripe-dynamiccache#72]
Re:
https://github.com/tractorcow/silverstripe-dynamiccache/blob/master/code/DynamicCacheControllerExtension.php#L36

Why not make one of the classes implement `flushable` and then add the following static method:

    public static function flush()
    {
        DynamicCache::inst()->clear();
    }

**Comment by tractorcow** [comment]
Ok sounds fair. :)
