### ISSUE TITLE
this module does not work in 3.7.0?

### ISSUE THREAD

**Issue by sunnysideup** [tractorcow/silverstripe-dynamiccache#73]
![image](https://user-images.githubusercontent.com/167154/41207360-ae91b496-6d68-11e8-9dd2-0e560c2d4ce2.png)

**Comment by tractorcow** [comment]
Oh no that's a problem.

**Comment by sunnysideup** [comment]
what I dont understand, and of course I am a nincompoop, is why 3.7 can break the module so badly when there are not API breaking changes.

Btw, did I mention this module rules BIG TIME?

**Comment by tractorcow** [comment]
Ok well I had better make a new version of this module for 4.x asap.

**Comment by tractorcow** [comment]
> what I dont understand, and of course I am a nincompoop, is why 3.7 can break the module so badly when there are not API breaking changes in a minor release AFAIK.

We take a lot of risks, but we catch a lot more errors that were once silent errors in the past. We need to get better at semver; We are still quite liberal with the rules...

**Comment by dhensby** [comment]
works fine for me?

**Comment by dhensby** [comment]
whoops - good point - I pointed at framework/main.php because this starts the session on every request

**Comment by dhensby** [comment]
gah - I hate adding exceptions in minor releases! this is so annoying :/
